config/routes.rb
FoodTruck::Application.routes.draw do
  match '(*any)' => redirect { |p, req| req.url.sub('//', '//www.') }, :constraints => { :subdomain => '' } 

  get   '/ping', to: 'root#ping', as: :ping

  resources :crafts

  post '/hover_crafts/sync', to: 'hover_crafts#sync'
  resources :hover_crafts

  get   '/tweet_api_accounts/verify_tweet_api_account_logins', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_logins
  get   '/tweet_api_accounts/:id/verify_tweet_api_account_login', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_login
  post  '/tweet_api_accounts/sync', to: 'tweet_api_accounts#sync'
  get   '/tweet_api_accounts/tweet_streams', to: 'tweet_api_accounts#tweet_streams', as: :tweet_streams
  get   '/tweet_api_accounts/:id/refresh', to: 'tweet_api_accounts#refresh', as: :refresh_tweet_api_account
  get   '/tweet_api_accounts/:id/toggle_streamer', to: 'tweet_api_accounts#toggle_streamer', as: :toggle_streamer_tweet_api_account
  resources :tweet_api_accounts

  root to: 'root#index'
 

  scope '/', controller: :root do
    get 'index', as: :home_page
    get ':name', to: :index
  end

  scope '/sudo', controller: :sudo do
    get 'index', as: :sudo_index
    get 'toggle_approved'
    get 'toggle_rejected'
    get 'toggle_essence'
    get 'toggle_theme'
  end

end

app/models/craft.rb
class Craft
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid

  # search ranking sort score
  field :ranking_score, type: Integer, default: 0

  # geocoder fields
  field :address, default: nil
  field :coordinates, type: Array, default: [] # does geocoder gem auto index this?
  # mongoid stores [long, lat] - which is backwards from normal convention
  # geocorder knows this, but expects [lat, lng]

  field :geo_location_history, :type => Array # for mobile crafts like a Food Truck

  # add all nizer.name to search_tags - be sure to update list when binding to a new nizer
  field :provider_id_tags, type: Array, default: [] # e.g. fb:facebook_id, yelp:yelp_id, @twitter_id etc. should be aliased to this field for a normalized id 
  field :provider_username_tags, type: Array, default: []  # e.g. fb:username, @twitter_handle

  field :essence_tags, type: Array, default: [] # food, fit, fun, travel, home
  field :theme_tags, type: Array, default: [] # truck, taco, sushi: weight-loss, yoga, etc


  field :href_tags, type: Array, default: []
  field :search_tags, type: Array, default: []

  # statuses
  field :status_strength, type: Integer
  field :rejected, type: Boolean, default: false
  field :approved, type: Boolean, default: false

  embeds_one :twitter_craft
  embeds_one :yelp_craft
  embeds_one :facebook_craft
  embeds_one :webpage_craft

  has_many :web_crafts, :dependent => :destroy
  # has_and_belongs_to_many :nizers # organizers

  index :provider_id_tags
  index :provider_username_tags
  index :essence_tags
  index :theme_tags
  index :href_tags
  index :search_tags

  geocoded_by :address
  reverse_geocoded_by :coordinates
  before_save :geocode_this_location! # auto-fetch coordinates

  def self.service() CraftService.instance end
  def service() CraftService.instance end

  def self.materialize_from_twitter_id(tid, default_address=nil, tweet_stream_id=nil)
    service.materialize_from_twitter_id(tid, default_address, tweet_stream_id)
  end

  def self.materialize(provider_id_username_or_href, provider = nil)
    service.materialize(provider_id_username_or_href, provider)
  end

  def self.where_twitter_exists
    crafts = Craft.all.reject{|c| c.twitter_craft.nil?} # find all crafts with a twitter webcraft
  end
  def self.without_twitter
    crafts = Craft.all.reject{|c| c.twitter_craft.present?} # find all crafts with missing twitter webcrafts
  end

  def tweet_stream_id() twitter.present? ? twitter.tweet_stream_id : nil end

  def is_for_food?(add_it = nil) is_in_essence_tags(:food, add_it) end
  def is_for_mobile_cuisine?(add_it = nil) is_in_essence_tags(:mobile_cuisine, add_it) end
  def is_for_fitness?(add_it = nil) is_in_essence_tags(:fitness, add_it) end
  def is_for_fun?(add_it = nil) is_in_essence_tags(:fun, add_it) end
  def is_for_home?(add_it = nil) is_in_essence_tags(:home, add_it) end
  alias_method :is_for_food_truck?, :is_for_mobile_cuisine?
  alias_method :is_for_foodtruck?, :is_for_mobile_cuisine?

  # add, remove or toggle a tag in the essence_tags
  def is_in_essence_tags(tag, add_it = nil)
    if :toggle.eql? add_it
      if essence_tags.include? tag
        is_in_essence_tags(tag, false) 
      else
        is_in_essence_tags(tag, true) 
      end
    elsif true.eql? add_it
      self.essence_tags << tag unless essence_tags.include? tag
      save!
      return true
    elsif false.eql? add_it
      self.essence_tags -= [ tag ]
      save!
      return false
    end
    essence_tags.include? tag
  end

  # add, remove or toggle a tag in the theme_tags
  def is_in_theme_tags(tag, add_it = nil)
    if :toggle.eql? add_it
      if theme_tags.include? tag
        is_in_theme_tags(tag, false) 
      else
        is_in_theme_tags(tag, true) 
      end
    elsif true.eql? add_it
      self.theme_tags << tag unless theme_tags.include? tag
      save!
      return true
    elsif false.eql? add_it
      self.theme_tags -= [ tag ]
      save!
      return false
    end
    theme_tags.include? tag
  end

  # geocoding  aliases
  alias_method :ip_address, :address
  alias_method :ip_address=, :address=

  def latitude() coordinates.last end
  alias_method :lat, :latitude

  def latitude=(lat) coordinates ||= [0,0]; coordinates[1] = lat end
  alias_method :lat=, :latitude=

  def longitude() coordinates.first end
  alias_method :lng, :longitude
  alias_method :long, :longitude

  def longitude=(lng) coordinates[0] = lng end
  alias_method :lng=, :longitude=
  alias_method :long=, :longitude=
  # /geocoding  aliases

  # geo point hash representation
  def geo_point() { lat:lat, lng:lng } end
  def geo_point=(latlng_hash)
    lt   = latlng_hash[:latitude]   if latlng_hash[:latitude].present?
    lt ||= latlng_hash[:lat]        if latlng_hash[:lat].present?

    ln   = latlng_hash[:longitude]  if latlng_hash[:longitude].present?
    ln ||= latlng_hash[:long]       if latlng_hash[:long].present?
    ln ||= latlng_hash[:lng]        if latlng_hash[:lng].present?

    self.lat = lt
    self.lng = ln
    { lat:lat, lng:lng }
  end
  alias_method :geo_coordinate, :geo_point
  alias_method :geo_coordinate=, :geo_point=
  # /geo point hash representation

  def map_pins
    {
      "#{_id}" => {
        name: name,
        lat: lat,
        lng: lng,
        website: website, 
        now_active: now_active?
      }
    }
  end

  def bind(web_craft)
    web_craft_list = *web_craft 
    web_craft_list.each do |wc|
      self.build_twitter_craft(wc.attributes)   if wc.provider.eql :twitter
      self.build_yelp_craft(wc.attributes)      if wc.provider.eql :yelp
      self.build_facebook_craft(wc.attributes)  if wc.provider.eql :facebook
      self.build_webpage_craft(wc.attributes)   if wc.provider.eql :webpage

      self.provider_id_tags << wc.web_craft_id unless (wc.web_craft_id.present? and self.provider_id_tags.include?(wc.web_craft_id))
      self.provider_username_tags << wc.username unless (wc.username.present? and self.provider_username_tags.include?(wc.username))
      self.href_tags << wc.href unless (wc.href.present? and self.href_tags.include?(wc.href))
      self.href_tags << wc.website unless (wc.website.present? and self.href_tags.include?(wc.website))
      self.address = wc.address if (:yelp==wc.provider || ( wc.address.present? and not self.address.present?) )
      self.coordinates = wc.coordinates if (:yelp==wc.provider || ( wc.coordinates.present? and not self.coordinates.present?) )
    end
    save
  end

  # def migrate_web_crafts
  #   puts "migrating #{_id}"
  #   d = ['_id', '_type', 'craft_id', 'href_tags', 'search_tags', 'created_at', 'updated_at', 'timeline', 'oembed', 'reviews', 'snippet_text', 'snippet_image_url']

  #   wc = web_crafts.twitter_crafts.first
  #   if wc
  #     puts "twitter #{wc._id}"
  #     atts = {}.merge wc.attributes
  #     d.map{|k| atts.delete k}    
  #     self.build_twitter_craft atts
  #   end

  #   wc = web_crafts.yelp_crafts.first
  #   if wc
  #     puts "yelp #{wc._id}"
  #     atts = {}.merge wc.attributes
  #     d.map{|k| atts.delete k}    
  #     self.build_yelp_craft atts
  #   end

  #   wc = web_crafts.facebook_crafts.first
  #   if wc
  #     puts "facebook #{wc._id}"
  #     atts = {}.merge wc.attributes
  #     d.map{|k| atts.delete k}    
  #     self.build_facebook_craft atts
  #   end

  #   wc = web_crafts.webpage_crafts.first
  #   if wc
  #     puts "webpage #{wc._id}"
  #     atts = {}.merge wc.attributes
  #     d.map{|k| atts.delete k}    
  #     self.build_webpage_craft atts
  #   end

  #   save
  # end

  # def twitter() twitter_craft end
  # def yelp() yelp_craft end
  # def facebook() facebook_craft end
  # def webpage() webpage_craft end

  # def yelp() web_crafts.yelp_crafts.first end
  # def flickr() web_crafts.flickr_crafts.first end
  # def webpage() web_crafts.webpage_crafts.first end
  # def twitter() web_crafts.twitter_crafts.first end
  # def facebook() web_crafts.facebook_crafts.first end
  # def you_tube() web_crafts.you_tube_crafts.first end
  # def google_plus() web_crafts.google_plus_crafts.first end

  # def yelp() nil end
  # def flickr() nil end
  # def webpage() nil end
  # def twitter() nil end
  # def facebook() nil end
  # def you_tube() nil end
  # def google_plus() nil end



  # Derive the Craft's Brand
  def name
    x = twitter_craft.name if twitter_craft.present?
    x ||= yelp_craft.name if yelp_craft.present?
    x ||= facebook_craft.name if facebook_craft.present?
    x
  end

  def description
    x = twitter_craft.description if twitter_craft.present?
    x ||= yelp_craft.description if yelp_craft.present?
    x ||= facebook_craft.description if facebook_craft.present?
    x
  end

  def last_tweet_html
    if twitter_craft.present? and twitter_craft.oembed.present?
      x = twitter_craft.oembed['html'].html_safe
    else
      x = nil
    end
    x
  end

  def how_long_ago_was_last_tweet
    return @how_long_ago_was_last_tweet if @how_long_ago_was_last_tweet.present?
    x = Util.how_long_ago_was(last_tweeted_at) if last_tweeted_at.present?
    x ||= nil
    @how_long_ago_was_last_tweet = x
  end

  def now_active?
    time = last_tweeted_at
    return false if time.nil?

    time = time + (-Time.zone_offset(Time.now.zone))
    2.days.ago < time # consider this craft to be active if there was a tweet in the last 2 days
  end

  def last_tweeted_at
    return @last_tweeted_at if @last_tweeted_at.present?
    # if twitter.present? and twitter.timeline.present? and twitter.timeline.first.present? and twitter.timeline.first["created_at"].present?      
    #   @last_tweeted_at = twitter.timeline.first["created_at"]
    #   @last_tweeted_at = @last_tweeted_at.to_time if @last_tweeted_at.present?
    # else
    #   @last_tweeted_at = nil
    # end
    @last_tweeted_at
  end

  def website
    # first see if there is a website specified
    x = yelp_craft.website if yelp_craft.present?

app/controllers/crafts_controller.rb
class CraftsController < ApplicationController
  # GET /crafts
  # GET /crafts.json
  def index
    @look_for = params[:q] || params[:look_for] || "food truck"
    @radius = params[:r] || params[:radius] || 100 # miles
    @page = params[:page] || 1

    # on click:
    # 1. get website YelpService.website_for_yelp_listing(q)
    # 2. load cratfs
    # 3. auto verify
    # 3. change/edit twitter handle/ facebook page / website url
    # 4. verify

    puts "=====================#{@geo_city}, #{@geo_state}, #{@look_for}, #{@page}"
    # @yelp_results = YelpService.food_trucks_in_city(@geo_city, @geo_state, @look_for, @page)
    @yelp_results = YelpService.food_trucks_in_city('santa monica', 'ca', @look_for, @page)
    puts @yelp_results
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: nil }
    end
 end


  # GET /crafts/find
  # GET /crafts/find.json
  def capture
    @url = Web.as_url(params[:url])
    @social_crafts = Web.web_craft_map(@url)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @craft }
    end
  end

  # GET /crafts/1
  # GET /crafts/1.json
  def show
    @craft = Craft.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @craft }
    end
  end

  # GET /crafts/new
  # GET /crafts/new.json
  def new
    # @craft = Craft.new

    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @craft }
    # end
  end

  # GET /crafts/1/edit
  def edit
    @craft = Craft.find(params[:id])
  end

  # POST /crafts
  # POST /crafts.json
  def create
    @look_for = params[:look_for]
    @near = params[:near]

    if (@look_for.looks_like_url?)
      u = URI.parse(@look_for.downcase)
      u = URI.parse("http://#{@look_for.downcase}") if u.host.nil?
      capture_craft_url =@look_for if u.host
      @craft = Craft.materialize(capture_craft_url)
    else
      # see if we can parse the search term and find it
    end

    respond_to do |format|
      if @craft
        format.html { redirect_to @craft, notice: 'Craft was materialized.' }
        format.json { render json: @craft, status: :created, location: @craft }
      else
        format.html { render action: "new" }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /crafts/1
  # PUT /crafts/1.json
  def update
    @craft = Craft.find(params[:id])

    respond_to do |format|
      if @craft.update_attributes(params[:craft])
        format.html { redirect_to @craft, notice: 'Craft was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @craft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crafts/1
  # DELETE /crafts/1.json
  def destroy
    @craft = Craft.find(params[:id])
    @craft.destroy

    respond_to do |format|
      format.html { redirect_to crafts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/crafts_helper.rb
module CraftsHelper
end

app/views/crafts/_craft_header.html.haml
.header
  .id
    %img.logo{src:"#{craft.profile_image_url}"}
    .name-and-activity
      %h2.name.ellipsis
        = "#{craft.name}"
      - if craft.how_long_ago_was_last_tweet
        .last-activity
          %img{src:'/assets/twitter/twitter-bird.png'}
          %span= craft.how_long_ago_was_last_tweet
    - if craft.yelp_craft.present?
      .yelp
        .logo
          %a.logo.yelp_logo_50x25{href:craft.yelp_craft.href, target: :_blank}
        / .rating-reviews
        /   .rating
        /     %img.star.rating{src:craft.yelp_craft.rating_img_url_large}
        /   .reviews
        /     = "#{craft.yelp_craft.review_count} reviews"

app/views/crafts/_craft_info.html.haml
.overview.cloth
  = render 'crafts/craft_overview', craft: craft
.activity.cloth
  = render '/crafts/craft_twitter_timeline', craft: craft
  = render '/crafts/craft_yelp_reviews', craft: craft

app/views/crafts/_craft_overview.html.haml
.stats.right
  = render '/crafts/craft_social_stats', craft: craft
.bio.left
  .cut
    .description
      = "#{craft.description}"
    .footer
      .url
        %a{href:craft.website}
          = "#{craft.website}"
  .social-buttons
    / https://developers.facebook.com/docs/reference/plugins/like/
    / https://dev.twitter.com/docs/follow-button
    - if craft.twitter_craft
      %iframe.tweet-follow-button.left{ allowtransparency:"true", frameborder:0, scrolling:"no", src:"//platform.twitter.com/widgets/follow_button.html#screen_name=#{craft.twitter_craft.screen_name}&align=left&button=grey&show_count=true&show_screen_name=true&lang=en"}
    - if craft.facebook_craft
      %iframe.facebook-like-button.right{ allowTransparency:"true", frameborder:0, scrolling:"no", src:"//www.facebook.com/plugins/like.php?href=#{u craft.facebook_craft.href}&layout=button_count&width=90&show_faces=false&send=false&action=like&colorscheme=light&font&height=21&appId=146598735467471"}          

  / .location
  /   = "#{craft.location}"
  /   .location-footer
  /     = craft.geo_enabled ? "(Geo Enabled!)" : "(Not Geo Enabled)"
  /     = craft.geo_point.to_json 

app/views/crafts/_craft_social_stats.html.haml
.social-stats
  .cut
    %ul
      / Yelp does not allow agregating or blending of their review count with other information  
      / - if yelp.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong= Util.short_human_number(yelp.review_count)
      /     Yelp reviews

      / - if craft.twitter_craft.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong= Util.short_human_number(craft.twitter_craft.statuses_count)
      /     tweets
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong= Util.short_human_number(craft.twitter_craft.followers_count)
      /     followers
      / - if craft.yelp_craft.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong= craft.yelp_craft.rating
      /     craft.yelp_craft rating
      / - if craft.twitter_craft.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong 1-5
      /     craft.twitter_craft activity
      / - if craft.facebook_craft.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong 1-5
      /     craft.facebook_craft activity
      / %li
      /   %img.indicator{src:"/assets/transparent-indicator.png"}
      /   %strong 1-5
      /   local distance
      /  facebook like button already shows # of likes
      / - if craft.facebook_craft.present?
      /   %li
      /     %img.indicator{src:"/assets/transparent-indicator.png"}
      /     %strong= Util.short_human_number(craft.facebook_craft.likes)
      /     FB likes

      / %li
      /   %img.indicator{src:"/assets/transparent-indicator.png"}
      /   %strong= craft.twitter_craft.friends_count
      /   Twitter friends

app/views/crafts/_craft_twitter_oembed.html.haml
- if craft.last_tweet_html.present?
  .last-tweet
    .oembed
      = craft.last_tweet_html
    - if craft.how_long_ago_was_last_tweet
      .last-activity
        %img{src:'/assets/twitter/twitter-bird.png'}
        %span= craft.how_long_ago_was_last_tweet

app/views/crafts/_craft_yelp_reviews.html.haml
- if craft.yelp_craft.present?
  .yelp-reviews.right
    / - yelp.reviews.each do |review|
    /   - user = review['user']
    /   %blockquote.cut.yelp-review
    /     .vcard.author
    /       %a{href:"http://www.yelp.com/user_details?userid=#{user['id']}"}
    /         %span.avatar
    /           %img.phto{src:user['image_url']}
    /         %span.fn
    /           = user['name']
    /         %span.star-rating
    /           %img{src: review['rating_image_url']}
    /         %a.yelp-follow-button{href: "http://www.yelp.com/following_user/add?dst_user_id=#{user['id']}&previous_url=#{u request.url}"}
    /           %i
    /           %span.label
    /             Follow
    /     .entry
    /       = review['excerpt']
    /     .footer
    /       .how-long-ago
    /         = Util.how_long_ago_was(Time.at(review['time_created']))
    /       %a.view-details{href:"http://www.yelp.com/biz/#{yelp.yelp_id}#hrid:#{review['id']}"}
    /         read more

app/views/crafts/_crafts_nav.html.haml
#nav.pageScrollerNav.standardNav.right.light
  - if @crafts.present?
    %ul
      - @crafts.each do |craft|
        %li
          %a.ellipsis{href:"##{craft.name}"}= craft.name

app/views/crafts/_form.html.haml
<%= form_for(@craft) do |f| %>
  <% if @craft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@craft.errors.count, "error") %> prohibited this craft from being saved:</h2>

      <ul>
      <% @craft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/crafts/capture.html.haml
=@url
- @social_crafts.each do |service, hash|
  = render("/crafts/web_crafts/#{service}", craft: hash[:craft]) if hash[:craft].present?

%hr
/ %iframe{src:"#{@url}", width:'90%', height: '80%'}

app/views/crafts/edit.html.haml
%h1 Editing craft

= render 'form'

= "#{link_to 'Show', @craft} |"
= "#{link_to 'Back', crafts_path}"

app/views/crafts/find.html.haml
%h1 Find A Craft On the Web

%form{action: :"/crafts/find", method: :get}
  %label Search For:
  %input{type: :text, name: :look_for, value: @look_for, placeholder: '@twitter_handle, url or search term'}
  %label Near:
  %input.med{type: :text, name: :near, value: @near, placeholder: 'adress, city, state or zip (optional)'}
  %button{type: :submit}
= link_to 'Back', crafts_path


- if @capture_craft_url.present?
  %div{onclick:"capture_craft('#{@capture_craft_url}')"}
    open @look_for

  :javascript
    function capture_craft(url) {
      capture_url = '/crafts/capture?url='+url
      openNewWindow(capture_url)
    }

    $(capture_craft('#{@capture_craft_url}'));

app/views/crafts/index.html.haml
%h1 Search for Existing Crafts

%form#add{action: crafts_path, method: :post}
  %input#look_for_yelp_listing{type: :hidden, name: :look_for, value: ''}

%form{action: crafts_path, method: :get}
  %label Search For:
  %input{type: :text, name: :look_for, value: @look_for, placeholder: '@twitter_handle, url or search term'}
  %label Near:
  %input.med{type: :text, name: :place, value: @place, placeholder: 'adress, city, state or zip (optional)'}
  %button{type: :submit}

#wrapper
  #main
    / - if @target_interest[:location][:metro_kw].present? and @target_interest[:location][:metro_kw] != @target_interest[:location][:city_kw]
    - if @yelp_results.present?      
      .yelp-results
        .total= @yelp_results['total']
        -  @yelp_results['businesses'].each do |biz|
          .yelp-listing{:"data-yelp-id" => biz['id'], style: 'padding: 10px; border: 1px solid blue;'}
            - if biz['is_closed']
              .closed MIGHT BE CLOSED!
            %img{src: biz['image_url'] }
            .name= biz['name']
            %img{src:biz['rating_img_url']}
            .review-count= biz['review_count']
            .address= "#{biz['location']['address']}, #{biz['location']['city']} #{biz['location']['state_code']}"
            %a.href{href:biz['url']}
              =biz['url']
            .snippet
              %img{src: biz['snippet_image_url']}
              .text= biz['snippet_text']
:javascript
  $(function(){
    $('a.href').on('click', function(event){
      event.stopPropagation();
      event.preventDefault();
      var look_for = $(this).attr('href');
      $('input[id="look_for_yelp_listing"]').attr('value', look_for);
      alert( $('input[id="look_for_yelp_listing"]').attr('value') ) ;
      $('#add').submit();
      return false;
    })
  })

app/views/crafts/new.html.haml
%h1 Find A Craft On the Web

%form{action: crafts_path, method: :post}
  %label Search For:
  %input{type: :text, name: :look_for, value: @look_for, placeholder: '@twitter_handle, url or search term'}
  %label Near:
  %input.med{type: :text, name: :place, value: @place, placeholder: 'adress, city, state or zip (optional)'}
  %button{type: :submit}
= link_to 'Back', crafts_path

app/views/crafts/show.html.haml
.section
  = render '/crafts/craft', craft: @craft

#geomap-wrapper
  .geomap.cut