config/routes.rb
FoodTruck::Application.routes.draw do
  match '(*any)' => redirect { |p, req| req.url.sub('//', '//www.') }, :constraints => { :subdomain => '' } 

  get   '/ping', to: 'root#ping', as: :ping

  resources :crafts

  post '/hover_crafts/sync', to: 'hover_crafts#sync'
  resources :hover_crafts

  get   '/tweet_api_accounts/verify_tweet_api_account_logins', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_logins
  get   '/tweet_api_accounts/:id/verify_tweet_api_account_login', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_login
  post  '/tweet_api_accounts/sync', to: 'tweet_api_accounts#sync'
  get   '/tweet_api_accounts/tweet_streams', to: 'tweet_api_accounts#tweet_streams', as: :tweet_streams
  get   '/tweet_api_accounts/:id/refresh', to: 'tweet_api_accounts#refresh', as: :refresh_tweet_api_account
  get   '/tweet_api_accounts/:id/toggle_streamer', to: 'tweet_api_accounts#toggle_streamer', as: :toggle_streamer_tweet_api_account
  resources :tweet_api_accounts

  root to: 'root#index'
 

  scope '/', controller: :root do
    get 'index', as: :home_page
    get ':name', to: :index
  end

  scope '/sudo', controller: :sudo do
    get 'index', as: :sudo_index
    get 'toggle_approved'
    get 'toggle_rejected'
    get 'toggle_essence'
    get 'toggle_theme'
  end

end

app/controllers/sudo_controller.rb
class SudoController < ApplicationController
  def index
    @look_for = params[:look_for] || params[:q]
    @radius = params[:radius] || params[:r] || 100 # miles
    @page = params[:page] || params[:p] || '1' # page
    @page = @page.to_i

    js_var(look_for: @look_for, radius: @radius, geo_place: @geo_place, geo_coordinates: @geo_coordinates)

    @crafts = Craft.near(@geo_coordinates, @radius).desc(:ranking_score) if @geo_coordinates
    @crafts ||= Craft.near(@geo_place, @radius).desc(:ranking_score) if @geo_place

    @total_crafts_count = @crafts.count
    limit = RESULTS_PER_PAGE
    skip = (@page-1) * RESULTS_PER_PAGE

    @crafts = @crafts.skip(skip).limit(limit)

    @total_pages = 1 + (@total_crafts_count/RESULTS_PER_PAGE).to_i
    js_var(total_crafts_count: @total_crafts_count, page: @page, total_pages: @total_pages)

    if @look_for.present?
      @crafts = @crafts.where(search_tags: @look_for)  if @crafts.present?
      @crafts ||= Craft.where(search_tags: @look_for)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: nil }
    end
  end

  def toggle_approved
    respond_to do |format|
      format.json do
        @craft = Craft.find(params[:id])
        render json: nil and return if @craft.nil?
        @craft.rejected = false
        @craft.approved = @craft.approved ? false : true
        @craft.save!
        render json: { status: @craft.approved }
      end
    end
  end

  def toggle_rejected
    respond_to do |format|
      format.json do
        @craft = Craft.find(params[:id])
        render json: nil and return if @craft.nil?
        @craft.approved = false
        @craft.rejected = @craft.rejected ? false : true
        @craft.save!
        render json: { status: @craft.rejected }
      end
    end
  end

  def toggle_essence
    respond_to do |format|
      format.json do
        @craft = Craft.find(params[:id])
        @essence = Craft.find(params[:essence])
        render json: nil and return if ( @craft.nil? or @essence.nil?)
        @craft.is_in_essence_tags @essence, :toggle
        render json: {essence_tags: @craft.essence_tags }
      end
    end
  end

  def toggle_theme
    respond_to do |format|
      format.json do
        @craft = Craft.find(params[:id])
        @theme = Craft.find(params[:theme])
        render json: nil and return if ( @craft.nil? or @theme.nil?)
        @craft.is_in_theme_tags @theme, :toggle
        render json: {theme_tags: @craft.theme_tags }
      end
    end
  end
      
end

app/views/sudo/index.html.haml
- @show_locator = sudo_index_path
- @locator_submit_url = sudo_index_path

#list
  #craft-list
    / - if @target_interest[:location][:metro_kw].present? and @target_interest[:location][:metro_kw] != @target_interest[:location][:city_kw]
    - if @crafts.present?
      - @crafts.each do |craft|
        - status = 'approved' if craft.approved.present?
        - status = 'rejected' if craft.rejected.present?
        - status ||= ''
        - status << ' essenced' if craft.essence_tags.present?
        - status << ' themed' if craft.theme_tags.present?
        .sudo-craft{class: status, :'data-craft-id' => craft._id}
          .toolbar
            .button.approve{class: "#{craft.approved}"}
              approve
            .button.essence.foodtruck{class: "#{craft.is_for_foodtruck?}"}
              food truck
            .button.essence.food{class: "#{craft.is_for_food?}"}
              food
            .button.essence.fitness{class: "#{craft.is_for_fitness?}"}
              fitness
            .button.essence.fun{class: "#{craft.is_for_fun?}"}
              fun
            .button.essence.home{class: "#{craft.is_for_home?}"}
              home
            .button.reject{class: "#{craft.rejected}"}
              reject
          .section
            = render '/crafts/craft', craft: craft
  #loading-crafts
    .section
      .canvas
        .loadinginprogress

/ %a.add-a-craft{href: href_for(new_craft_path) }
/   add a new food truck
#geomap-wrapper
  .geomap.cut

#right-sidebar
  / =render 'crafts/crafts_nav'

:javascript 
  $(function(){

    $('.button.approve').live('click', function(){
      var $approve_button = $(this)
      var $sudo_craft = $approve_button.parents('.sudo-craft');
      var $reject_button = $sudo_craft.find('.reject')
      var craft_id = $sudo_craft.data('craft-id');

      var endpoint = $.extend({}, js_var.request);
      endpoint.path = '/sudo/toggle_approved';
      endpoint.query_parameters = { 'id': craft_id }
      var href = make_url(endpoint);
      $.get(href, function(data){
        var status = data.status;
        $sudo_craft.removeClass('approved').removeClass('rejected');
        $approve_button.removeClass('true').removeClass('false');
        $reject_button.removeClass('true').removeClass('false').addClass('false');
        if (status) {
          $sudo_craft.addClass('approved')
          $approve_button.addClass('true');
        }
        else {
          $approve_button.addClass('false');
        }
      })
    })

    $('.button.reject').live('click', function(){
      var $reject_button = $(this)
      var $sudo_craft = $reject_button.parents('.sudo-craft');
      var $approve_button = $sudo_craft.find('.approve')
      var craft_id = $sudo_craft.data('craft-id');

      var endpoint = $.extend({}, js_var.request);
      endpoint.path = '/sudo/toggle_rejected';
      endpoint.query_parameters = { 'id': craft_id }
      var href = make_url(endpoint);
      $.get(href, function(data){
        var status = data.status;
        $sudo_craft.removeClass('approved').removeClass('rejected');
        $reject_button.removeClass('true').removeClass('false');
        $approve_button.removeClass('true').removeClass('false').addClass('false');

        if (status) {
          $sudo_craft.addClass('rejected')
          $reject_button.addClass('true');
        }
        else {
          $reject_button.addClass('false');
        }
      })
    })


  })

  $('body').on('user:scrolled-to-75%', $.debounce( 1000, true, function(){
      console.log('scrolled!')
      // return if there are no more pages to fetch
      var href = make_url_for_next_page();
      if (!href) {
        // +++ show add more crafts 
        return; // no more pages to fetch
      }
      js_var.current_page++;
      $('.loadinginprogress').show();
      $.get(href, function(data){
        $('.loadinginprogress').hide();
        $('#craft-list').append($(data).find('#craft-list .sudo-craft').hide());
        $('#craft-list .sudo-craft').fadeIn();
      })
      // go get more results and add to main-content
      // $('#main-content').append(h1)  
    })
  )

app/views/sudo/tweet_streams.html.haml
%h1= "#{@craft_streams.all.count} Craft Streams"
%h1= "#{@threads_started} threads started"
%h1= "#{@threads.count} threads running"