config/routes.rb
FoodTruck::Application.routes.draw do
  match '(*any)' => redirect { |p, req| req.url.sub('//', '//www.') }, :constraints => { :subdomain => '' } 

  get   '/ping', to: 'root#ping', as: :ping

  resources :crafts

  post '/hover_crafts/sync', to: 'hover_crafts#sync'
  resources :hover_crafts

  get   '/tweet_api_accounts/verify_tweet_api_account_logins', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_logins
  get   '/tweet_api_accounts/:id/verify_tweet_api_account_login', to: 'tweet_api_accounts#verify_tweet_api_account_logins', as: :verify_tweet_api_account_login
  post  '/tweet_api_accounts/sync', to: 'tweet_api_accounts#sync'
  get   '/tweet_api_accounts/tweet_streams', to: 'tweet_api_accounts#tweet_streams', as: :tweet_streams
  get   '/tweet_api_accounts/:id/refresh', to: 'tweet_api_accounts#refresh', as: :refresh_tweet_api_account
  get   '/tweet_api_accounts/:id/toggle_streamer', to: 'tweet_api_accounts#toggle_streamer', as: :toggle_streamer_tweet_api_account
  resources :tweet_api_accounts

  root to: 'root#index'
 

  scope '/', controller: :root do
    get 'index', as: :home_page
    get ':name', to: :index
  end

  scope '/sudo', controller: :sudo do
    get 'index', as: :sudo_index
    get 'toggle_approved'
    get 'toggle_rejected'
    get 'toggle_essence'
    get 'toggle_theme'
  end

end

app/models/tweet_api_account.rb
class TweetApiAccount
  # used by application (not Users) to connect to twitter api (via Twitter or TweetStream Gem)
  # default Twitter password: 'foodTRUCK2012'
  include Mongoid::Document
  include Mongoid::Timestamps
  include Geocoder::Model::Mongoid

  field :twitter_id, type: Integer, default: nil
  field :is_tweet_streamer, type: Boolean, default: false
  field :login_ok, type: Boolean, default: false
  field :screen_name, default: nil
  field :name, default: nil
  field :description, default: nil
  field :friends_count, type: Integer, default: 0
  field :followers_count, type: Integer, default: 0
  field :friend_ids, type: Array, default: []
  field :oauth_config, type: Hash, default: { auth_method: :oauth }
  # geocoder fields
  field :address, default: nil
  field :coordinates, type: Array, default: [] # does geocoder gem auto index this?
  # mongoid stores [long, lat] - which is backwards from normal convention
  # geocorder knows this, but expects [lat, lng]

  geocoded_by :address
  reverse_geocoded_by :coordinates
  before_save :geocode_this_location! # auto-fetch coordinates

  scope :streams, where(is_tweet_streamer: true).and(login_ok: true)
  scope :admins, where(is_tweet_streamer: false).and(login_ok: true)

  def self.lookup(id_or_screen_name)
    id = "#{id_or_screen_name}"
    account = where(twitter_id: id.to_i).first if id.integer?
    account = where(screen_name: id_or_screen_name).first if not id.integer?
    account
  end

  def stream_service() TweetStreamService.instance end
  def self.stream_service() TweetStreamService.instance end

  def twitter_service() TwitterService.instance end
  def self.twitter_service() TwitterService.instance end
    
  def remote_pull!
    raise "!! account login is unverified #{screen_name}[#{twitter_id}]" unless (login_ok or verify_login)
    # client = Twitter::Client.new(twitter_oauth_config)
    client = twitter_service.twitter_client(self)
    update_from_twitter_client(client)
  rescue Exception => e
    puts e.message
    false
  end

  def twitter_client() twitter_service.twitter_client(self) end
  def self.next_admin_account!() twitter_service.next_admin_account! end

  def verify_login
    twitter_service.delete_twitter_client(self) # remove any old clients that may have stale auth info
    client = twitter_service.twitter_client(self)
    login_ok = update_from_twitter_client(client)
    puts ":: #{screen_name}: Login OK = #{login_ok}"
    update_attributes(login_ok: login_ok)
    login_ok
  rescue Exception => e
    puts "!! #{screen_name}: login failed #{e.message}"
    update_attributes(login_ok: false)
    false
  end

  def consumer_key() oauth_config['consumer_key'] end
  def consumer_key=(val) oauth_config['consumer_key'] = val end
  def consumer_secret() oauth_config['consumer_secret'] end
  def consumer_secret=(val) oauth_config['consumer_secret'] = val end
  def oauth_token() oauth_config['oauth_token'] end
  def oauth_token=(val) oauth_config['oauth_token'] = val end
  def oauth_token_secret() oauth_config['oauth_token_secret'] end
  def oauth_token_secret=(val) oauth_config['oauth_token_secret'] = val end

  def follow(twitter_username_or_id)
  end

  def unfollow(twitter_username_or_id)
  end

  def streaming_status
    self.is_tweet_streamer ? TweetStreamService.instance.stream_status(self.screen_name) : :off
  end

  def twitter_oauth_config
    self.oauth_config.twitter_oauth_config
  end
 
  def self.beam_up(url='www.food-truck.me', path='tweet_api_accounts/sync.json', use_ssl=false, cookies = {}, port=nil)
    TweetApiAccount.all.each do |s|
      s.beam_up(url, path, use_ssl, cookies, port)
    end
  end
  def beam_up(url='www.food-truck.me', path='tweet_api_accounts/sync.json', use_ssl=false, cookies = {}, port=nil)
    params = {}
    params[:tweet_api_account] = self.to_json
    r = Web.http_post(url, path, params, use_ssl, cookies, port)
    puts r
    r
  end

# geocoding  aliases
  alias_method :ip_address, :address
  alias_method :ip_address=, :address=

  def latitude() coordinates.last end
  alias_method :lat, :latitude

  def latitude=(lat) coordinates ||= [0,0]; coordinates[1] = lat end
  alias_method :lat=, :latitude=

  def longitude() coordinates.first end
  alias_method :lng, :longitude
  alias_method :long, :longitude

  def longitude=(lng) coordinates[0] = lng end
  alias_method :lng=, :longitude=
  alias_method :long=, :longitude=
  # /geocoding  aliases
private
  def geocode_this_location!
    # +++ enable geocoder geo caching! so we are not geocoding both the webcraft and the craft
    if self.lat.present? and (new? or changes[:coordinates].present?)
      puts "coordinates changed!"
      reverse_geocode # udate the address
      # +++ add {time, coordinates, address} to geo_location_history
    elsif address.present? and (new? or changes[:address].present?)
      puts "address changed!"
      geocode # update lat, lng
    end
    return true
  end


  def update_from_twitter_client(client)
    user = client.user
    self.twitter_id = user.id
    self.screen_name = user.screen_name
    self.name = user.name
    self.description = user.description
    self.address = user.location
    self.friends_count = user.friends_count
    self.followers_count = user.followers_count

    # manage friend list
    friends = client.friend_ids
    unfriended = self.friend_ids - friends.ids # +++ TODO unbind TwitterCrafts that are bound to this TweetStreamAccount (if this is a TweetStreamAccount)
    self.friend_ids = friends.ids
    self.save!
  end

end

app/controllers/tweet_api_accounts_controller.rb
class TweetApiAccountsController < BasicAuthProtectionController
  protect_from_forgery except: :sync

  def sync
    hash = JSON.parse(params[:tweet_api_account])
    status = sync_account(hash)
    respond_to do |format|
      format.html { render text: status} # index.html.erb
      format.json { render json: {status: status}.to_json }
    end
  end

  # GET /tweet_api_accounts
  # GET /tweet_api_accounts.json
  def index
    # TweetStreamService.instance.start_listening

    @tweet_api_accounts = TweetApiAccount.all
    @tweet_streams = TweetApiAccount.streams
    @streamers_count = @tweet_streams.count

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweet_api_accounts }
    end
  end

  def refresh
    @tweet_api_account = TweetApiAccount.find(params[:id])
    @tweet_api_account.remote_pull!
    respond_to do |format|
      format.html { redirect_to tweet_api_accounts_url }
      format.json { render json: {status: :ok } }
    end
  end

  def verify_tweet_api_account_logins
    if params[:id]
      @account= TweetApiAccount.find(params[:id])
      @account.verify_login if @account.present?
    else
      TweetApiAccount.verify_logins
    end
    respond_to do |format|
      format.html { redirect_to tweet_api_accounts_url }
      format.json { render json: {status: :ok } }
    end
  end

  def toggle_streamer
    @tweet_api_account = TweetApiAccount.find(params[:id])
    if @tweet_api_account.present?
      @tweet_api_account.is_tweet_streamer = ! @tweet_api_account.is_tweet_streamer
      @tweet_api_account.save!
      if @tweet_api_account.is_tweet_streamer
        @tweet_api_account.remote_pull! # take this opportunity to also update the profile
        TweetStreamService.instance.start_stream(@tweet_api_account) 
      else
        TweetStreamService.instance.stop_stream(@tweet_api_account)
      end
    end
    respond_to do |format|
      format.html { redirect_to tweet_api_accounts_url }
      format.json { render json: {status: :ok } }
    end
  end

  # GET /tweet_api_accounts/1
  # GET /tweet_api_accounts/1.json
  def show
    @tweet_api_account = TweetApiAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet_api_account }
    end
  end

  # GET /tweet_api_accounts/new
  # GET /tweet_api_accounts/new.json
  def new
    @tweet_api_account = TweetApiAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet_api_account }
    end
  end

  # GET /tweet_api_accounts/1/edit
  def edit
    @tweet_api_account = TweetApiAccount.find(params[:id])
  end

  # POST /tweet_api_accounts
  # POST /tweet_api_accounts.json
  def create
    account = {
      screen_name: params[:tweet_api_account][:screen_name],
      oauth_config: params[:tweet_api_account].twitter_oauth_config
    }
    # client = Twitter::Client.new(account[oauth_config])
    # pull client.user(account[:twitter_username])
    # set twitter_id
    # set following_ids
    # set address based on location
    @tweet_api_account = TweetApiAccount.new(account)

    respond_to do |format|
      if @tweet_api_account.remote_pull!
        format.html { redirect_to @tweet_api_account, notice: 'Tweet stream account was successfully created.' }
        format.json { render json: @tweet_api_account, status: :created, location: @tweet_api_account }
      else
        format.html { render action: "new" }
        format.json { render json: @tweet_api_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tweet_api_accounts/1
  # PUT /tweet_api_accounts/1.json
  def update
    account = {
      twitter_id: params[:tweet_api_account][:twitter_id],
      screen_name: params[:tweet_api_account][:screen_name],
      oauth_config: params[:tweet_api_account].twitter_oauth_config
    }
    # client = Twitter::Client.new(account[oauth_config])
    # pull client.user(account[:twitter_username])
    # set twitter_id
    # set following_ids
    # set address based on location
    @tweet_api_account = TweetApiAccount.find(account)

    respond_to do |format|
      if @tweet_api_account.update_attributes(account)
        format.html { redirect_to @tweet_api_account, notice: 'Tweet stream account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet_api_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweet_api_accounts/1
  # DELETE /tweet_api_accounts/1.json
  def destroy
    @tweet_api_account = TweetApiAccount.find(params[:id])
    @tweet_api_account.destroy

    respond_to do |format|
      format.html { redirect_to tweet_api_accounts_url }
      format.json { head :no_content }
    end
  end


  # def sync_tweet_api_account
  #   hash = JSON.parse(params[:tweet_api_account])
  #   clazz = TweetApiAccount
  #   status = sync(hash, clazz)
  #   respond_to do |format|
  #     format.html { render text: status} # index.html.erb
  #     format.json { render json: {status: status}.to_json }
  #   end
  # end

private
  def sync_account(hash)
    puts "sync in progress for TweetApiAccount: #{@hash}"

    # remove derived atts that need to be regenerated
    hash.delete('_id')
    hash.delete('created_at')
    hash.delete('updated_at')
    hash.delete('login_ok')
    puts "============== #{hash['screen_name']}"
    puts hash

    (@account = TweetApiAccount.where(twitter_id: hash['twitter_id']).first) if hash['twitter_id'].present?
    @account ||= TweetApiAccount.where(screen_name: hash['screen_name']).first if hash['screen_name'].present?

    if @account.present?
      puts "Updating #{@account.screen_name} [#{@account._id}].."
      @account.update_attributes(hash)
    else
      puts "Creating #{hash['screen_name']}"
      @account = TweetApiAccount.create(hash)
    end

    @account.save if @account.present?
    @account.remote_pull!

    if @account.present?
      status = 'ok' 
    else
      status = 'error'
    end
    puts "============== sync #{status}: #{hash['screen_name']}"
    status
  end

end

app/views/tweet_api_accounts/_form.html.haml
= form_for(@tweet_api_account) do |f|
  - if @tweet_api_account.errors.any?
    #error_explanation
      %h2
        = pluralize(@tweet_api_account.errors.count, 'error') 
        prohibited this tweet_api_account from being saved:

      %ul
      - @tweet_api_account.errors.full_messages.each do |msg|
        %li= msg

  = f.hidden_field :twitter_id
  .field
    = f.label :screen_name
    %br
    = f.text_field :screen_name
  .field
    = f.label :consumer_key
    %br
    = f.text_field :consumer_key
  .field
    = f.label :consumer_secret
    %br
    = f.text_field :consumer_secret
  .field
    = f.label :oauth_token
    %br
    = f.text_field :oauth_token
  .field
    = f.label :oauth_token_secret
    %br
    = f.text_field :oauth_token_secret
  .actions
    = f.submit

app/views/tweet_api_accounts/index.html.haml
%h1 Tweet API Accounts
%h2= "#{@streamers_count} Total Streams"
- total_friends_count = 0
.button
    %a{href: verify_tweet_api_account_logins_path}
        verify logins
%table
    %tr
        %th Account
        %th Login
        %th # Friends
        %th Refresh
        %th Screen name
        %th Name
        %th Description
        %th Address
        %th # Followers
        %th

    - @tweet_api_accounts.each do |tweet_api_account|
        - total_friends_count += tweet_api_account.friends_count
        %tr
            %td= link_to "#{tweet_api_account.streaming_status}", toggle_streamer_tweet_api_account_path(tweet_api_account)
            %td
                - if not tweet_api_account.login_ok
                    %a{href: verify_tweet_api_account_login_path(tweet_api_account)}
                        failed
                - else
                    ok
            %td= tweet_api_account.friends_count
            %td= link_to tweet_api_account.twitter_id, refresh_tweet_api_account_path(tweet_api_account)
            %td= link_to tweet_api_account.screen_name, tweet_api_account
            %td= tweet_api_account.name
            %td= tweet_api_account.description
            %td
                = tweet_api_account.address
                %br
                = tweet_api_account.coordinates

            %td= tweet_api_account.followers_count
            / %td= hide_middle tweet_api_account.consumer_key
            / %td= hide_middle tweet_api_account.consumer_secret
            / %td= hide_middle tweet_api_account.oauth_token
            / %td= hide_middle tweet_api_account.oauth_token_secret
            %td= link_to 'Destroy', tweet_api_account, confirm: 'Are you sure?', method: :delete

%br
%h2= "Following #{total_friends_count} total Food Trucks"
%br

= link_to 'New Tweet stream account', new_tweet_api_account_path

app/views/tweet_api_accounts/new.html.haml
%h1 New Tweet API Account

= render 'form'

= link_to 'Back', tweet_api_accounts_path

app/views/tweet_api_accounts/show.html.haml
%p#notice
  = notice

%p
  %b Twitter:
  = @tweet_api_account.twitter_id

%p
  %b Screen Name:
  = @tweet_api_account.screen_name

%p
  %b Description:
  = @tweet_api_account.description

%p
  %b # Friends:
  = @tweet_api_account.friends_count

%p
  %b # Followers:
  = @tweet_api_account.followers_count

%p
  %b Address:
  = @tweet_api_account.address
  %br
  = @tweet_api_account.coordinates

%p
  %b Consumer key:
  = @tweet_api_account.consumer_key

%p
  %b Consumer secret:
  = @tweet_api_account.consumer_secret

%p
  %b Oauth token:
  = @tweet_api_account.oauth_token

%p
  %b Oauth token secret:
  = @tweet_api_account.oauth_token_secret


<!-- = link_to 'Edit', edit_tweet_api_account_path(@tweet_api_account) -->
<!-- | -->
= link_to 'Back', tweet_api_accounts_path